name: UGames
options:
  bundleIdPrefix: games.yandex.wrap
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: en
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    CODE_SIGNING_ALLOWED: NO
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGN_IDENTITY: ""
    CODE_SIGN_ENTITLEMENTS: ""
    PROVISIONING_PROFILE_SPECIFIER: ""
    DEVELOPMENT_TEAM: ""
    ENABLE_BITCODE: NO
    TARGETED_DEVICE_FAMILY: "1,2"

targets:
  UGames:
    type: application
    platform: iOS
    sources:
      - path: UGames
        excludes:
          - "Info.plist"
    resources:
      - path: UGames/Resources
        type: folder
    info:
      path: UGames/Info.plist
      properties:
        CFBundleDisplayName: U-Games
        CFBundleShortVersionString: "0.1.3"
        CFBundleVersion: "4"
        UIRequiresFullScreen: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchScreen:
          UIColorName: black
        NSAppTransportSecurity:
          NSAllowsArbitraryLoadsInWebContent: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: games.yandex.wrap
        INFOPLIST_FILE: UGames/Info.plist
